# Eat Safe, Love

## Notebook Set Up

In [40]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd
import regex as re

In [41]:
# Create an instance of MongoClient
mongo = MongoClient(port = 27017)

In [42]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [43]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [44]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [47]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}
results = establishments.find(query)

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)

# Display the first document in the results using pprint
pprint(results[0])

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646bdb2db97ec01445fcd842'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'geocode[latitude]': None,
 'geocode[longitude]': None,
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(list(results))
df

# Display the number of rows in the DataFrame
len(df.index)

# Display the first 10 rows of the DataFrame
df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode,RightToReply,Distance,NewRatingPending,meta,links,latitude,longitude,geocode[latitude],geocode[longitude]
0,646bdb2db97ec01445fcd842,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
1,646bdb2db97ec01445fcdbc5,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
2,646bdb2db97ec01445fcdecd,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
3,646bdb2db97ec01445fce0bd,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
4,646bdb2db97ec01445fce0cd,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
5,646bdb2db97ec01445fcea69,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
6,646bdb2db97ec01445fcec8a,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None,None,None
7,646bdb2db97ec01445fd01b5,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
8,646bdb2db97ec01445fd0602,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
9,646bdb2db97ec01445fd0e07,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"$and":
             [
                 {"LocalAuthorityName": {"$regex": "London"}},
                 {"RatingValue": {"$gt": 4}}
             ]
        }
results = establishments.find(query)

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)

# Display the first document in the results using pprint
pprint(results[0])

{'AddressLine1': 'Cherry Garden Pier',
 'AddressLine2': 'Cherry Garden Street Rotherhithe',
 'AddressLine3': 'Charlton',
 'AddressLine4': '',
 'BusinessName': 'Mv City Cruises Erasmus',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.8731788858,
 'FHRSID': 1130836,
 'LocalAuthorityBusinessID': 'PI/000034075',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'TN4 8HR',
 'RatingDate': '2021-05-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('646bdb2db97ec01445fcf585'),
 'geocode': {'latitude': 51.1236228942871, 'longitude': 0.249255999922752},
 'geocode[latitude]': None,
 'geocode[longitude]': None,
 'latitude': None,
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1130836',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 5}}

In [9]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(results)
df

# Display the number of rows in the DataFrame
len(df.index)

# Display the first 10 rows of the DataFrame
df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode,RightToReply,Distance,NewRatingPending,meta,links,latitude,longitude,geocode[latitude],geocode[longitude]
0,646bdb2db97ec01445fcf585,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
1,646bdb2db97ec01445fd0ed1,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
2,646bdb2db97ec01445fd0ed2,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
3,646bdb2db97ec01445fd15d8,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
4,646bdb2db97ec01445fd36ea,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
5,646bdb2db97ec01445fd3aca,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
6,646bdb2db97ec01445fd3acb,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
7,646bdb2db97ec01445fd3acc,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
8,646bdb2db97ec01445fd3ca4,294523,0,PI/000015222,Jet Centre,Restaurant/Cafe/Canteen,1,London City Airport,Royal Docks London,,...,"{'longitude': 0.0405181497335434, 'latitude': ...",,4649.485870,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None
9,646bdb2db97ec01445fd3ca8,294616,0,PI/000016269,Caffè Nero,Restaurant/Cafe/Canteen,1,London City Airport Airside Departure Lounge,Royal Docks London,,...,"{'longitude': 0.040518, 'latitude': 51.504808}",,4649.485929,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None,None,None

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [51]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

lat_lower = latitude - degree_search
lat_upper = latitude + degree_search

lon_lower = longitude - degree_search
lon_upper = longitude + degree_search

query = {"$and":
             [
                 {"geocode.latitude": {"$gt": lat_lower, "$lt": lat_upper}},
                 {"geocode.longitude": {"$gt": lon_lower, "$lt": lon_upper}},
                 {"RatingValue": 5}
             ]
        }

sort = [("scores.Hygiene", 1)]

results = establishments.find(query).sort(sort).limit(5)

# Print the results
pprint(list(results))

# Convert result to Pandas DataFrame
df = pd.DataFrame(list(results))
df

[{'AddressLine1': '130 - 132 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Volunteer',
  'BusinessType': 'Pub/bar/nightclub',
  'BusinessTypeID': 7843,
  'ChangesByServerID': 0,
  'Distance': 4646.965634598608,
  'FHRSID': 694609,
  'LocalAuthorityBusinessID': 'PI/000116619',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2019-08-05T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('646bdb2db97ec01445fd30a7'),
  'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
  'geocode[latitude]': None,
  'geocode[longitude]': None,
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694609',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Plumstead Manor School Old Mill Road',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Plumstead Manor Nursery',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4646.9740101340385,
  'FHRSID': 695241,
  'LocalAuthorityBusinessID': 'PI/000179088',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1QG',
  'RatingDate': '2021-06-16T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('646bdb2db97ec01445fd30b9'),
  'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
  'geocode[latitude]': None,
  'geocode[longitude]': None,
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695241',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '35 Lakedale Road',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Atlantic Fish Bar',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4646.974611855838,
  'FHRSID': 694478,
  'LocalAuthorityBusinessID': 'PI/000086506',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1PR',
  'RatingDate': '2021-06-16T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('646bdb2db97ec01445fd30be'),
  'geocode': {'latitude': 51.4867296, 'longitude': 0.0912164},
  'geocode[latitude]': None,
  'geocode[longitude]': None,
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694478',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '144 - 146 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Iceland',
  'BusinessType': 'Retailers - supermarkets/hypermarkets',
  'BusinessTypeID': 7840,
  'ChangesByServerID': 0,
  'Distance': 4646.946071297699,
  'FHRSID': 695223,
  'LocalAuthorityBusinessID': 'PI/000178842',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2019-11-13T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('646bdb2db97ec01445fd3076'),
  'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
  'geocode[latitude]': None,
  'geocode[longitude]': None,
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695223',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Howe and Co Fish and Chips - Van 17',
  'BusinessType': 'Mobile caterer',
  'BusinessTypeID': 7846,
  'ChangesByServerID': 0,
  'Distance': 4646.95593107927,
  'FHRSID': 1380578,
  'LocalAuthorityBusinessID': '14425',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SE',
  'RatingDate': '2021-11-11T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('646bdb2db97ec01445fd3083'),
  'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
  'geocode[latitude]': None,
  'geocode[longitude]': None,
  'latitude': None,
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1380578',
             'rel': 'self'}],
  'longitude': None,
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}]

Empty DataFrame
Columns: []
Index: []

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [52]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

pipeline = [
    {"$match": {"scores.Hygiene": 0}},
    {"$group": {"_id": "$LocalAuthorityName", "matches": {"$sum": 1}}},
    {"$sort": {"matches": -1}}
]

results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
len(list(results))

# Print the first 10 results
pprint(list(results)[0:10])

[{'_id': 'Thanet', 'matches': 1130},
 {'_id': 'Greenwich', 'matches': 882},
 {'_id': 'Maidstone', 'matches': 713},
 {'_id': 'Newham', 'matches': 711},
 {'_id': 'Swale', 'matches': 686},
 {'_id': 'Chelmsford', 'matches': 680},
 {'_id': 'Medway', 'matches': 672},
 {'_id': 'Bexley', 'matches': 607},
 {'_id': 'Southend-On-Sea', 'matches': 586},
 {'_id': 'Tendring', 'matches': 542}]

In [54]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(results)
# Display the number of rows in the DataFrame
len(df)
# Display the first 10 rows of the DataFrame
df.head(10)

               _id  matches
0           Thanet     1130
1        Greenwich      882
2        Maidstone      713
3           Newham      711
4            Swale      686
5       Chelmsford      680
6           Medway      672
7           Bexley      607
8  Southend-On-Sea      586
9         Tendring      542